[tool.poetry]
name = "parser-frs"
version = "0.1.0"
description = ""
authors = ["Marusya <pavlenkoma13@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Scrapy = "^2.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
